Models/ErrorViewModel.cs
namespace dotnetportfolio.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/BiographyController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using dotnetportfolio.Models;
namespace dotnetportfolio.Controllers;
public class BiographyController :Controller{
    
    public IActionResult Bio(){
        return View();
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using dotnetportfolio.Models;

namespace dotnetportfolio.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"]="Home Page";
}
<!DOCTYPE html>
    <html>
        <head>
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

            <style>
                body{
                    background-color: black;
                    background-image: url("show.png");

                }
                
                .name{
                    width: auto;
                    background-color:black;
                    text-align: left;
                    color: white;
                    font-family: "Sofia", sans-serif;
                    font-size: 50px;
                }
                .container{
                    width: 100%;
                    display: flex;
                    margin: 10px;
                    flex-wrap: wrap;
                }
                .item{
                    color:white;
                    margin: 10px;
                }
                .bio{
                    color:white;
                    font-family: "Trirong", serif;
                    font-size: 30px;
                }
                .bio1{
                    color:white;
                    font-size: 15px;
                    line-height: 9px;
                }
                .birtyear {
                    display: flex;
                }
                .seeyear{
                    display: flex;
                }
                .high{
                    display: flex;
                }
                .bachelor{
                    display: flex;
                }
                .by{
                    margin-left: 160px;
                    font-size: 15px;
                }
            </style>
        </head>
        <body>
            <div class="name"> 
                 Prabesh Tamang 
            </div>
          <div class="container">
            <div class="item">
            </div>
            <div class="bio">Short Biography <hr> 
            <div class="bio1">
               <p>Hi i am Prabesh Tamang. I am Computer Science Student</p>  
               <p>Hi i am Prabesh Tamang. I am Computer Science Student</p>  
               <p>Hi i am Prabesh Tamang. I am Computer Science Student</p>  

            </div>
            <hr>
            <div class="bio2">
                <div class="birtyear">2001 
                    <div class="by"> Date of BIrth </div>
                      </div>
                <hr>
                <div class="seeyear">2017
                    <div class="by">Passing SEE Exam

                    </div>
                </div>
                <hr>
                <div class="high">2019
                    <div class="by">Passing +2 Exam </div>
                </div>
                <hr>
                <div class="bachelor">2020
                    <div class="by">Join Bachelor in BSc.CSIT </div>
                </div>
            </div>
            
            </div>
            <div class="item">one</div>
            <div class="item">one</div>

          </div>


        </body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - prabesh</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/dotnetportfolio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">prabesh </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">PRIVACY</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Biography" asp-action="Bio">BIOGRAPHY</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">BLOGS</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">PROJECTS</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">CONTACT ME</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - prabesh - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/biography/Bio.cshtml
@{
    ViewData["Title"]="Biography";
}
<divd> THis is biography of prabesh </divd>